### ISSUE TITLE
Unable to run sling from docker image

### ISSUE THREAD

**Issue by Codykilpatrick** [slingdata-io/sling-cli#105]
Hey all! I was previously running sling with the python wrapper and the CLI with no issue but switched over to running via the docker image Version: 1.0.66. I am currently running on Mac 14.1.2.

The issue:
Running this command: `docker run --rm -i slingdata/sling run -c task.json`
Generates this error:
```
~ 
~ could not parse task configuration (see docs @ https://docs.slingdata.io/sling-cli)
~ Error parsing cfgBytes
yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `task.json` into sling.Config
```
I'm sure my task.json is valid though because running: `sling run -c task.json` leads to success. I also created an identical task.yaml and observed the same things with that.

When that failed I tried to just tackle it with a command line using the docker image and ran into a different problem. The following command:
```
docker run slingdata/sling run  --src-conn 'mysql://root:insecure_password@localhost:3306/forerunner_legacy' \
          --tgt-conn 'postgresql://forerunner_owner:insecure_password@localhost:5432/forerunner?sslmode=disable' \
          --src-stream 'SELECT heading, bearing_time_configuration, date, id, HEX(pixels) AS hex_representation FROM forerunner_legacy.bearing_time_record WHERE {incremental_where_cond};' \
          --tgt-object 'forerunner_public.bearing_time_record_staging' \
          --mode incremental \
          --primary-key id \
          --update-key date
```
Generates this error:
```
fatal:
~ 
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~ 
~ execution failed
~ Could not connect to: mysql:// (mysql)
~ could not connect to database
dial tcp 127.0.0.1:3306: connect: connection refused
```

And again If I run it with my local sling with the exact same options its succeeds. 
Any help at all would be greatly appreciated!

**Comment by flarco** [comment]
hey there, the error message > `cannot unmarshal !!str 'task.json' into sling.Config` leads me to believe the `task.json` file is not being passed into the docker volume. Sling attempts to parse the `-c` flag value as yaml if it cannot find the file on disk. I think I will improve that error to be more helpful.

Regarding your second error, `localhost` (`127.0.0.1`) attempts to connect inside of docker (probably not where your database is running). Since it's probably running on your host machine (outside of docker), try your macbook hostname? if still not working, you might have to mess with docker network settings.

**Comment by flarco** [comment]
Try `docker run --rm -v /path/to/task.json:task.json -i slingdata/sling run -c task.json`

**Comment by flarco** [comment]
Closing since this isn't a sling issue.
