### ISSUE TITLE
DB to File ( Parquet + S3 ) replication creates files without .parquet extension when total rows synced < target_option max rows

### ISSUE THREAD

**Issue by ShahBinoy** [slingdata-io/sling-cli#111]
I have been trying to use replication to move data between MySQL and S3+Parquet.
Using the file below, the S3 file is correct Parquet, but it is missing the `.parquet` extension
below just creates 1 file in S3 `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_10`

```json
{
  "source": "ACADIA",
  "target": "S3_LAKE_ZONE_A",
  "defaults": {
    "mode": "incremental",
    "object": "dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}_{MM}_{DD}/",
    "update_key": "updated_on",
    "target_options": {
      "format": "parquet"
    }
  },
  "streams": {
    "acadia.jhi_user": {
      "update_key": "last_modified_date",
      "disabled": false
    }
  },
  "env": {
    "SLING_LOADED_AT_COLUMN": true,
    "SLING_STREAM_URL_COLUMN": true,
    "path_prefix": "${FRUGAL_DATA_LANDING_PREFIX}",
    "SLING_SHOW_PROGRESS": "false",
    "SLING_DISABLE_TELEMETRY": "false",
    "SLING_HOME_DIR": "/Users/bshah/workspace/data-engg/data-lake-workflows/src/vibrent_common/sling/../../sling"
  }
}
```

whereas when I limited the max rows to a small number as in replication.json file below, it created a few 100s of `part-xxxx-xx.parquet` files under the folder `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_10/`

```json
{
  "source": "ACADIA",
  "target": "S3_LAKE_ZONE_A",
  "defaults": {
    "mode": "incremental",
    "object": "dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}_{MM}_{DD}/",
    "update_key": "updated_on",
    "target_options": {
      "file_max_rows": 1000,
      "format": "parquet"
    }
  },
  "streams": {
    "acadia.jhi_user": {
      "update_key": "last_modified_date",
      "disabled": false
    }
  },
  "env": {
    "SLING_LOADED_AT_COLUMN": true,
    "SLING_STREAM_URL_COLUMN": true,
    "path_prefix": "${FRUGAL_DATA_LANDING_PREFIX}",
    "SLING_SHOW_PROGRESS": "false",
    "SLING_DISABLE_TELEMETRY": "false",
    "SLING_HOME_DIR": "/Users/bshah/workspace/data-engg/data-lake-workflows/src/vibrent_common/sling/../../sling"
  }
}
```

**Comment by flarco** [comment]
Hi, yes that's how it's built. See https://github.com/flarco/dbio/blob/main/filesys/fs.go#L683-L685

When you are not using `file_max_rows` or `file_max_bytes`, sling will output in a single file. When it's a single file output, you can just append the `.parquet` suffix to the object name. You could just put `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}_{MM}_{DD}.parquet` for the object for single file?

Sling allows freedom in naming for single files, the thought behind was that some people may not want a default extension. For example, if someone wants to output a delimited file with delimiter `\t`, they may want to name the extension `.tsv` instead of default `.csv`. 

When folder output, there is less flexibility, as sling will append the extension by default since the sub-files are just partitions of the chosen `format`.

Thinking of it, I can see what you mean, with the inconsistent behavior... Perhaps the default extension should not be put in the partitioned files in folder output 🤔. Partitioned files are usually less important, right, so it could just stay without extension. Thoughts?

**Comment by ShahBinoy** [comment]
IMO, some sane defaults should be there. 
ie. 
`data-000.parquet` .. why extension `parquet` ? because my `format` is `parquet`
if there is already a provision for `format` keyword i was hoping it would use the `.parquet` as extension too. 

To your point, if they needed `tsv`, `tsv` being a known format should be supported internally for `\t` separator as default, just as `csv` defaults to `,` as separator

Conventionally when the path ends in `/` it means that file needs to be dumped at that path prefix ( "folder" )

Since that didnt work I thought, okay, if `/` is not accepted, i tried putting in `<path>/*.parquet` but it then uses `*.parquet` verbatim resulting in `<fullpath>/*.parquet/xxx` which does not randomize my files.

Another aspect is that cloud storage conventions and many tools recognize folder hierarchy with **HIVE** naming conventions, and those tools leverage globbing of wildcard based paths too

* PyArrow: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html#pyarrow-parquet-parquetdataset
* DuckDb https://duckdb.org/docs/data/partitioning/hive_partitioning.html
* Polars: https://github.com/pola-rs/polars/issues/4347


**So I have not verified what happens when I put the path as below?**
`dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}_{MM}_{DD}.parquet` but my table rows are greater than the max rows. 

I havent checked if it creates files like:
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024_01_10-000.parquet`
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024_01_10-001.parquet`
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024_01_10-002.parquet`

If it does then I might be able to still play around with it like putting path as 
`dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}-{MM}-{DD}/data.parquet`
for my desired affect which will generate files like 
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024-01-10/data-000.parquet`
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024-01-10/data-001.parquet`
* `dev-binoy/elt/data_landing/{source_name}/{stream_table}/date=2024-01-10/data-002.parquet`

**Comment by ShahBinoy** [comment]
Hi,
Following up, I used the object path like below:

`"object": "dev-binoy/elt/data_landing/{source_name}/{stream_table}/date={YYYY}_{MM}_{DD}/data.parquet"`, hoping that it will auto-generate files by enumerating on `data-xxx.parquet` 

When I changed the max_row to 100,000 then it auto generated partitions

but the path for each was 

* `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_11/data.parquet/part.01.0001.parquet`
* * `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_11/data.parquet/part.01.0002.parquet`
* * `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_11/data.parquet/part.01.0003.parquet`
* * `dev-binoy/elt/data_landing/acadia/jhi_user/date=2024_01_11/data.parquet/part.01.0004.parquet`

So currently it does not allow to put extension without reducing the file_max_row.

Few cents towards why extension and auto-enumeration needed
1. Extension gives a bit verbosity and clarity
2. Globbing on extension is possible
3. "Folder" hierarchy with auto-generated file names with extension appears intuitive for users to view files
4. To force extension, the file_max_row needs to be known and or hard-coded, but acutal data sizes in db tables could vary

Hope above points makes my situation a stronger case to address it

**Comment by flarco** [comment]
Thanks for the details. Sure, we can keep the auto-extension on partitioned files.

One aspect needs addressing, once you set the `file_max_rows` to a non-zero value, it will always create a folder with enumerated files (with extension), whether the file rows reach that value or not. So you could always set that value to above zero, and it will auto-add the extension, in a folder partitioned style. I think this is what you're wanting, right?

I just tried to confirm with setting `file_max_rows`, and it always creates a folder (and appends the extension) whether the number rows reach that value, see log below for a table with 1k rows, along with `file_max_rows` of 100k :

```
$ sling run --src-conn postgres \
  --src-stream public.accounts \
  --tgt-object file://./test2 \
  --tgt-options '{ file_max_rows: 100000, format: parquet }'

11:42PM INF connecting to source database (postgres)
11:42PM INF reading from source database
11:42PM INF writing to target file system (file)
11:42PM INF wrote 1000 rows [4,017 r/s] to file://./test2
11:42PM INF execution succeeded
```

Created folder and file: `test2/part.01.0001.parquet`

---

If you don't provide `file_max_rows`, it will always write to a single file, and this is where you would need to provide the extension yourself. I still don't think that the extension should be auto-provided in single-file mode when you can just provide it in the `object` input. I think it's confusing when a user will (likely) provide a target path, including the extension, only for sling to auto-append an extension again. Yes, we could write logic to detect if the user already provided a suffix, but that's more complication than needed (too much magic), since the user could provide upper case ext or could want to conform to some external requirement. For example, sling supports jsonlines. Some people use `.jsonl`, others use `.jsonlines`. In single file mode, they are free to choose their preferred extension (granted in folder mode, sling will append `.jsonl`).

---

Furthermore, let us consider these 2 commands:

`sling run --src-conn postgres --src-stream my_schema.my_table --tgt-object file://./my_table.parquet`
vs
`sling run --src-conn postgres --src-stream my_schema.my_table --tgt-object file://./my_table --tgt-options '{ format: parquet }'`

Both commands do the same thing, cause since `format` wasn't provided in the first, sling detects the extension and writes accordingly. IMHO, the first command is more intuitive, less verbose and the path comes out exactly as the user inputted, whereas the second command would auto-append `.parquet`. 

For folder styled (partitioned) output, currently user needs to specify  `file_max_rows`, and it will auto-append the extension every time, and the folder path provided will come out exactly as the user inputted.  Regarding the HIVE convention, I'm not sure that feasible ATM, since sling would need to split the steam into different folders based on a column value (lotta refactor for that). But I think most tools would still work just fine with the way sling splits it (only 1 folder level), right?

However, I do agree, that if the object path ends with `/`, then it should be treated as folder (with some default `file_max_rows` value, like 100k). That's more intuitive and like that we don't have to specify `file_max_rows` unless we don't want the default value.  Also, we could allow a custom extension for the partitioned files inside the folder 🤔, but thinking not since I'm trying to keep the number of options lean, it's adding up...

Thoughts?

**Comment by ShahBinoy** [comment]
I see your point about the auto-extension from the examples of `jsonl` vs `jsonlines`, so its okay if you dont infer it from the format.

Secondly if 

* Respecting the ending `/` and 
* Defaulting a setting value of `100k` for so max_rows 

will make sling generate files with enumerated names + extension then it serves the need for building datasets.

Hopefully that will be a small change :-)

**Comment by flarco** [comment]
OK, I actually settled on the `/*<extension>` styled suffix.

Reasons:
- It is explicit that the user wishes to partition files in a folder.
- Allows user to specify a custom extension. Can provide `*.parquet` or `*.part` or `*`. The latter 2 will require a valid `target.options.fomat`.
- Parsing the `/` at the end of the path is actually tricky for cloud systems, all of them have their own rules, so didn't really want to mess with that.

Changes (https://github.com/flarco/dbio/commit/f1fc07880e938642c153e8cc91980f30a2a9ffa0) are applied in #110 !

**Comment by flarco** [comment]
Released. Closing.
