### ISSUE TITLE
Shift to sub-process Architecture

### ISSUE THREAD

**Issue by flarco** [slingdata-io/sling-cli#117]
The thought is to shift the actual sling loading process to run inside a child process.

This will enable:
- Built-in multi-threading support (running streams concurrently) (https://github.com/slingdata-io/sling-cli/discussions/30)
- Capture the stream log output
- More resilience to Go panics and unexpected errors
- Support Retries

**Comment by flarco** [comment]
Closing, as it increases complexity unnecessarily. Determined that this should be handled externally.

**Comment by jmesterh** [comment]
Sad to see this closed, was hoping this would be implemented eventually? We use our in-house tool [Dumpty](https://github.com/stanfordmed/dumpty) to perform a nightly full extract of ~15k tables, many are >1TB with billions of rows. We have an 8-hour window before our connections get dropped by the nightly ETL, so Sling wouldn't finish in time. These awful multi-TB tables don't have CDC or "last-updated" column information for incremental extract (they come from a big-iron non-relational data source).

Dumpty extracts tables in parallel, and each table itself is multi-threaded based on calculated PK ranges. The idea is to saturate our 10Gb/s network link to extract the DB as fast as possible (while we are the only user). I know this is a _very_ specific use-case, but we'd love to switch to Sling since it's honestly a better product overall (and has incremental support for tables where we _do_ have incremental hints).

Anyway just thought I'd provide some food-for-thought on why someone might want this feature 😀

**Comment by flarco** [comment]
Thanks for sharing, will keep in mind.
