### ISSUE TITLE
 Batch size support

### ISSUE THREAD

**Issue by wearpants** [slingdata-io/sling-cli#138]
When reading from a database source, instead of one big/long running query, it would be nice to be able to run multiple `SELECT`s to a user-configurable batch size of N rows each (using ORDER BY update_key and LIMIT/OFFSET). Ideally these could be done in parallel in multiple threads (#30), but even sequential queries would be desirable to reduce load/row locking on the source database

**Comment by flarco** [comment]
This is already possible (sequentially), see the `Database ⇨ Database (Incremental / Backfill)` example in https://docs.slingdata.io/sling-cli/run/database-to-database. You could just keep looping with mode `incremental` and a value for `source_options.limit` (your batch size), it will pick up where you left off.

LIMIT/OFFSET could be a cool feature, will consider it.

There are plans to support concurrent streams: https://github.com/slingdata-io/sling-cli/issues/117

**Comment by wearpants** [comment]
OK but how do I know when to stop looping? I'm running sling as a task inside airflow not a continuous job

**Comment by flarco** [comment]
Well, I'm assuming you need to transfer large amounts of data due to backfill or first time transfer? I would increase the frequency in airflow (maybe every 10min, depending on how long the batch takes)? Even it is caught up while running frequently, it won't affect anything, the run will just end quickly (since it SELECT where `update_key` > `max(update_key from target)`. So when the runs are short, you could relax the frequency again.

**Comment by flarco** [comment]
Closing for now.
