### ISSUE TITLE
Oracle connection produces error "ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library"

### ISSUE THREAD

**Issue by SebastianArcq** [slingdata-io/sling-cli#206]
When I run
`export ORACLE_DB='oracle://user:mypassw@orcl.host:1521/db1'`
and then
`sling conns test ORACLE_DB `
I get the following error:
```
fatal:
~ could not connect to database
ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 0x0001): tried: 'libclntsh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' (no such file, not in dyld cache), 'libclntsh.dylib' (no such file)". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```

The same happens when I actually use  a real Oracle DB, but this shows that the error has nothing to do with the actual connection. 

I don't get this error message. Do I really need to install some Oracle client library to run Sling?

I'm running an M3 Macbook Pro on Sonoma 14.3.1 if that matters.

**Comment by flarco** [comment]
Hello Sebastian, thanks for all the details!

Unfortunately, yes, you do need the oracle client installed to use it. This is because sling uses a 3rd party driver (https://github.com/godror/godror) which requires it. There is this newer driver (https://github.com/sijms/go-ora) that doesn't require it, but it apparently has less features, and I'm guessing is less performant. I do plan to benchmark it to see if sling could use that.

If you don't want to install the oracle client on your machine, you can simply use the sling docker image (`slingdata/sling`). It has the oracle client bundled in there.

**Comment by flarco** [comment]
Closing. Feel free to re-open.
