### ISSUE TITLE
Enhancement: Update Audit Column in Target Table

### ISSUE THREAD

**Issue by gu-xie** [slingdata-io/sling-cli#46]
Sling currently replicates the data from source to target as is.
It would help immensely for post-sling processing patterns if there was a timestamp audit column to represent when the record was last updated.

Only `snapshot` option will populate an extra column of `_sling_loaded_at` to indicate when the data was loaded.
Would be great if we can enable this on other modes as a target option.

**Comment by flarco** [comment]
Ah, yes, it's built-in, just set the environment variable `SLING_LOADED_AT_COLUMN=true` before you run your task.

There is also the `SLING_STREAM_URL_COLUMN=true` setting if you are loading from files. It will write the source file path / URL.

If you are using a [replication YAML file](https://docs.slingdata.io/sling-cli/replication), you can add it in the `env` section so that the setting is persisted in the config file.

See https://github.com/slingdata-io/sling-cli/blob/9457055eb57e0844d91846871c30d4c473ea0f18/core/sling/config.go#L118C23-L118C45 for code reference.

Feedback from you, in general, do you think `SLING_LOADED_AT_COLUMN` should be set `true` by default?

**Comment by gu-xie** [comment]
This is perfect! I didn't see in the slingdata docs of any mention about `SLING_LOADED_AT_COLUMN=true`.

In general, I do think it should be set as `true` by default, however I do see most users are expecting the data to be a reflection of the source so I think `false` is okay. 
As long as we have a method for enabling this for those that do want it - that's good enough.

**Comment by flarco** [comment]
It's [here](https://docs.slingdata.io/sling-cli/environment#global-environment-variables) in the docs. I confess I added it after you asked about it :).

Great, thanks, I agree. Let's keep the default as `false`.
