### ISSUE TITLE
Oracle TNS for SSL/TLS connection

### ISSUE THREAD

**Issue by temminks** [slingdata-io/sling-cli#80]
Hi,

I'm trying to connect to an Oracle database using an encrypted connection. When using Java, I use a JDBC connection string like
`jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=my-host.db.com)(PORT=6666))(CONNECT_DATA=(SID=DB)))` and add the database server's certificate to my Java Keystore.

Sling has a connection property _tns_ for the Oracle connector ("The Oracle TNS string of the instance") but I was not able to set the value properly. In the end, though, I'd simply like to use an encrypted connection, so if there was a way to define that connection using the other parameters (host, schema, ...) or the url-style connection definition that would be fine, too. I already set up the (unencrypted) connection using the host/port/sid/schema properties.

**Comment by flarco** [comment]
Hi, can you check out https://docs.slingdata.io/connections/database-connections/oracle?

Since you're using a `SID`, the url should be something like: `oracle://myuser:mypass@my-host.db.com:6666/<sid>`

For the encrypted part, I'm not too sure. Looking in the docs of the driver [here](https://godror.github.io/godror/doc/connection.html), I see the `ssl_server_cert_dn` parameter. So perhaps try to play with that? Something like
```
oracle://myuser:mypass@my-host.db.com:6666/<sid>?ssl_server_cert_dn="cn=sales,cn=Oracle Context Server,dc=us,dc=example,dc=com"&sdu=8128&connect_timeout=60
```

Let me know how that goes, Sling is currently using an older version of the driver, so will probably update to the latest version next release. I think I'll also revise the parameters inputs.
