### ISSUE TITLE
Replicating Oracle table with BLOB

### ISSUE THREAD

**Issue by sandhein** [slingdata-io/sling-cli#89]
Hi,
I currently use your tool to replicate data between Oracle and Snowflake. I love the ease of use of this tool, thanks for sharing it!
It works great for most tables, but I face a problem when replicating a table with a BLOB column. 
The table I want to copy is named META_LOAD_DOCUMENT and contains a bunch of regular columns and one column of type BLOB named "DOCUMENT".
Sling throws an error when trying to do the COPY INTO the temp table.

Seams as if SLING is reading the BLOB as string.:
```
Error executing COPY INTO "***"."META_LOAD_DOCUMENT_TMP" ("LOAD_ID", "LOAD_STATUS", "CREATED_AT", "UPDATED_AT", "FILE_STATUS", "FILE_STORE_PATH", "DOCUMENT_FORMAT", "DOCUMENT", "DOCUMENT_ID", "DOCUMENT_TIMESTAMP", "DOCUMENT_TYPE")
FROM (
SELECT T.$1, T.$2, T.$3, T.$4, T.$5, T.$6, T.$7, T.$8, T.$9, T.$10, T.$11
FROM @***.***/"***"."META_LOAD_DOCUMENT_TMP"/2023***2***3T161901.873/part.01.0003.csv.zst as T
)
FILE_FORMAT = (
TYPE = CSV
RECORD_DELIMITER = '\n'
ESCAPE_UNENCLOSED_FIELD = NONE
FIELD_OPTIONALLY_ENCLOSED_BY='0x22'
EMPTY_FIELD_AS_NULL=TRUE
NULL_IF = ''
SKIP_HEADER=1
REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR = ABORT_STATEMENT

100082 (22000): Max LOB size (16777216) exceeded, actual size of parsed column is 583515701
```
Appreciate any help.

Sandra

**Comment by flarco** [comment]
Hi, sure. So this is happening Snowflake side. Could you post the whole log output after running with flag `-d` (debug mode)? Need to see the DDL of the temp table.

**Comment by flarco** [comment]
Actually, this looks like it's a Snowflake hard limit.

See
- https://stackoverflow.com/a/72490818
- https://community.snowflake.com/s/article/Max-LOB-size-exceeded

What is in the `DOCUMENT` field? is it JSON structured text? If so, you could tell sling it is a JSON column, by setting the source options `columns` to `{"document": "json"}`, and also set `flatten: true` so that sling will break apart the JSON fields into their own column inside the Snowflake table. See https://docs.slingdata.io/sling-cli/run/configuration#source.

If that's not an option, then you are out of luck, as this is a Snowflake limitation. The best thing I'm thinking is to omit that column by running a custom SQL stream (select all columns except that one, or trim the `DOCUMENT` column inside of oracle). (see https://docs.slingdata.io/sling-cli/run/database-to-database#database-database-custom-sql).

Let me know if any questions.
